Add row means imputation test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -12,6 +12,7 @@ workflows:
   test-with-cwl:
     jobs:
       - rep-bulk
+      - rep-bulk-with-imputation
 #          <<: *filter
 #      - test-dl-brca:
 #          <<: *filter
@@ -142,9 +143,6 @@ jobs:
     executor: ubuntu
     steps:
       - checkout
-#      - attach_workspace:
-#          at: /tmp/workspace
-#      - run: ls /tmp/workspace
       - run:
           name: Install dependencies to VM
           command: pip3 install cwltool
@@ -152,7 +150,9 @@ jobs:
           name: Run rep-bulk
           command: |
             cd ~/project/tumorDeconvAlgs/BayesDeBulk
-            cwltool bayes-de-bulk.cwl --expressionFile=../../toy_data/TOY_rna_expression_imputed.tsv --signatureMatrix=../../toy_data/TOY_signature_matrix.tsv
+            cwltool bayes-de-bulk.cwl \
+              --expressionFile=../../toy_data/TOY_rna_expression_imputed.tsv \
+              --signatureMatrix=../../toy_data/TOY_signature_matrix.tsv
           no_output_timeout: 1h
       - run:
           name: Test that TSV output was created
@@ -163,13 +163,28 @@ jobs:
                 echo "Test cases failed !!!"
                 exit 1
             fi
-# had to comment below because it wasn't needed for workflow
-#      - run:
-#          name: Test that Rdata file was created
-#          command: |
-#            if [ -f ~/project/tumorDeconvAlgs/repBulk/output_rep_bulk_gibbs.Rdata ]; then
-#                echo "output_rep_bulk_gibbs.Rdata successfully created!"
-#            else
-#                echo "Test cases failed !!!"
-#                exit 1
-#            fi
+  rep-bulk-with-imputation:
+    executor: ubuntu
+    steps:
+      - checkout
+      - run:
+          name: Install dependencies to VM
+          command: pip3 install cwltool
+      - run:
+          name: Run rep-bulk
+          command: |
+              cd ~/project/tumorDeconvAlgs/BayesDeBulk
+              cwltool bayes-de-bulk.cwl \
+                --expressionFile=../../toy_data/TOY_rna_expression_withNA.tsv \
+                --signatureMatrix=../../toy_data/TOY_signature_matrix.tsv \
+                --rowMeansImputation=TRUE
+          no_output_timeout: 1h
+      - run:
+          name: Test that TSV output was created
+          command: |
+            if [ -f ~/project/tumorDeconvAlgs/repBulk/*-deconv.tsv ]; then
+                echo "~/project/imputation/imputed_file.tsv successfully created!"
+            else
+                echo "Test cases failed !!!"
+                exit 1
+            fi
