updating mRNA/prot and also tests

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -149,18 +149,19 @@ jobs:
       - run:
           name: Test that TSV output was created
           command: |
-            if [ -f ~/project/tumorDeconvAlgs/repBulk/output_rep_bulk.tsv ]; then
+            if [ -f ~/project/tumorDeconvAlgs/repBulk/*-deconv.tsv ]; then
                 echo "~/project/imputation/imputed_file.tsv successfully created!"
             else
                 echo "Test cases failed !!!"
                 exit 1
             fi
-      - run:
-          name: Test that Rdata file was created
-          command: |
-            if [ -f ~/project/tumorDeconvAlgs/repBulk/output_rep_bulk_gibbs.Rdata ]; then
-                echo "output_rep_bulk_gibbs.Rdata successfully created!"
-            else
-                echo "Test cases failed !!!"
-                exit 1
-            fi
+# had to comment below because it wasn't needed for workflow
+#      - run:
+#          name: Test that Rdata file was created
+#          command: |
+#            if [ -f ~/project/tumorDeconvAlgs/repBulk/output_rep_bulk_gibbs.Rdata ]; then
+#                echo "output_rep_bulk_gibbs.Rdata successfully created!"
+#            else
+#                echo "Test cases failed !!!"
+#                exit 1
+#            fi
